version = "1.0"

[main]
name.en = "Configuration panel"
name.fr = "Panneau de configuration"
services = ["__APP__", "nginx"]

[main.limit_size]
name.en = "Upload limit size"
name.fr = "Téléchargement de fichiers"

[main.limit_size.php_upload_max_filesize]
ask.fr = "Taille limite d'un téléchargement en Mo"
ask.en = "Upload size limit (Mb)"
type = "number"
bind = "null"


[main.limit_size.photo_max_size]
ask.fr = "Taille limite d'une photo en Ko"
ask.en = "photo max size limit (Kb)"
type = "number"
bind = "MAX_PHOTO_SIZE:__INSTALL_DIR__/.env"

